### PR TITLE
Added support for Inline::C's "with" operator.

### LINKED ISSUE #4: Support Inline::C's `with => qw/Alien::OpenMP/,` semantics

### PR DESCRIPTION
**Pull request by oodler577**
Implemented Inline method for coupling more automagically
with Inline::C.

Resolves #4.

### CODE REVIEW

**Comment by mohawk2** [comment]
This looks really good now! I think putting the test in `xt` is a good call, but since it's a release test, can we change the CI from a manual installing of Inline::C to adding it to `develop.requires`?

**Comment by oodler577** [comment]
> This looks really good now! I think putting the test in `xt` is a good call, but since it's a release test, can we change the CI from a manual installing of Inline::C to adding it to `develop.requires`?

Added.

**Comment by oodler577** [comment]
> This looks really good now! I think putting the test in `xt` is a good call, but since it's a release test, can we change the CI from a manual installing of Inline::C to adding it to `develop.requires`?

@mohawk2 I believe we're in a good spot and all CI are passing now. Will wait patiently for your next pass, hopefully it will be the last one.

**Comment by oodler577** [comment]
@mohawk2 - are you waiting on anything else to approve this PR? I think I've addressed everything. Also, let me know if you'd like me to handle the release to CPAN process. Standing by ready to assist. Thank you

**Comment by oodler577** [comment]
any comments on this, @zmughal?

**Comment by zmughal** [comment]
Everything looks good to me! Tested locally as well.

<del>I only noticed that the  `xt/inline-c-with.t` test does not run on the CI. That's up to you if you want that as part of the CI feedback. You could add another step to install the develop-requires and run it.</del> <add>Edit: Sorry, just noticed the release testing in the matrix. Ignore this part!</add>

**Comment by oodler577** [comment]
Merging, all seems right in the World atm.

**Pull request merged**
